In [ ]:
#libraries
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [ ]:
#loading dataset
df = pd.read_csv('data.csv')
df.head()

,isbn13,isbn10,title,subtitle,authors,categories,thumbnail,description,published_year,average_rating,num_pages,ratings_count
0,9780002005883,0002005883,Gilead,NaN,Marilynne Robinson,Fiction,http://books.google.com/books/content?id=KQZCP...,A NOVEL THAT READERS and critics have been eag...,2004.0,3.85,247.0,361.0
1,9780002261982,0002261987,Spider's Web,A Novel,Charles Osborne;Agatha Christie,Detective and mystery stories,http://books.google.com/books/content?id=gA5GP...,A new 'Christie for Christmas' -- a full-lengt...,2000.0,3.83,241.0,5164.0
2,9780006163831,0006163831,The One Tree,NaN,Stephen R. Donaldson,American fiction,http://books.google.com/books/content?id=OmQaw...,Volume Two of Stephen Donaldson's acclaimed se...,1982.0,3.97,479.0,172.0
3,9780006178736,0006178731,Rage of angels,NaN,Sidney Sheldon,Fiction,http://books.google.com/books/content?id=FKo2T...,"A memorable, mesmerizing heroine Jennifer -- b...",1993.0,3.93,512.0,29532.0
4,9780006280897,0006280897,The Four Loves,NaN,Clive Staples Lewis,Christian life,http://books.google.com/books/content?id=XhQ5X...,Lewis' work on the nature of love divides love...,2002.0,4.15,170.0,33684.0

In [ ]:
df['thumbnail'][0]

'http://books.google.com/books/content?id=KQZCPgAACAAJ&printsec=frontcover&img=1&zoom=1&source=gbs_api'

In [ ]:
df.shape

(6810, 12)

In [ ]:
df.isnull().sum()

isbn13               0
isbn10               0
title                0
subtitle          4429
authors             72
categories          99
thumbnail          329
description        262
published_year       6
average_rating      43
num_pages           43
ratings_count       43
dtype: int64

In [ ]:
df.duplicated().sum()

np.int64(0)

In [ ]:
df.columns

Index(['isbn13', 'isbn10', 'title', 'subtitle', 'authors', 'categories',
       'thumbnail', 'description', 'published_year', 'average_rating',
       'num_pages', 'ratings_count'],
      dtype='object')

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6810 entries, 0 to 6809
Data columns (total 12 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   isbn13          6810 non-null   int64
 1   isbn10          6810 non-null   object
 2   title           6810 non-null   object
 3   subtitle        2381 non-null   object
 4   authors         6738 non-null   object
 5   categories      6711 non-null   object
 6   thumbnail       6481 non-null   object
 7   description     6548 non-null   object
 8   published_year  6804 non-null   float64
 9   average_rating  6767 non-null   float64
 10  num_pages       6767 non-null   float64
 11  ratings_count   6767 non-null   float64
dtypes: float64(4), int64(1), object(7)
memory usage: 638.6+ KB

#extracting top 50 books

In [ ]:
df_rating = df[['title','average_rating','ratings_count','categories','thumbnail','authors']]
df_rating.head()

,title,average_rating,ratings_count,categories,thumbnail,authors
0,Gilead,3.85,361.0,Fiction,http://books.google.com/books/content?id=KQZCP...,Marilynne Robinson
1,Spider's Web,3.83,5164.0,Detective and mystery stories,http://books.google.com/books/content?id=gA5GP...,Charles Osborne;Agatha Christie
2,The One Tree,3.97,172.0,American fiction,http://books.google.com/books/content?id=OmQaw...,Stephen R. Donaldson
3,Rage of angels,3.93,29532.0,Fiction,http://books.google.com/books/content?id=FKo2T...,Sidney Sheldon
4,The Four Loves,4.15,33684.0,Christian life,http://books.google.com/books/content?id=XhQ5X...,Clive Staples Lewis

In [ ]:
#removing null values
df_rating= df_rating.dropna(subset=['categories','thumbnail'])

In [ ]:
#filling null values
df_rating['authors'] = df_rating['authors'].fillna(' ')
df_rating['average_rating'] = df_rating['average_rating'].fillna(df['average_rating'].mean())
df_rating['ratings_count'] = df_rating['ratings_count'].fillna(0)

In [ ]:
df_rating = df_rating.reset_index(drop=True)

In [ ]:
df_popular = df_rating[df_rating['ratings_count']>=1000]

In [ ]:
df_popular = df_popular.sort_values(by='average_rating',ascending=False).reset_index(drop=True)

In [ ]:
df_popular = df_popular.head(50)
df_popular.head()

,title,average_rating,ratings_count,categories,thumbnail,authors
0,The Complete Calvin and Hobbes,4.82,31249.0,Comics & Graphic Novels,http://books.google.com/books/content?id=wmjG5...,Bill Watterson
1,Harry Potter,4.78,38872.0,Juvenile Fiction,http://books.google.com/books/content?id=DAAAA...,J. K. Rowling
2,It's a Magical World,4.76,23336.0,Humor,http://books.google.com/books/content?id=y1NVN...,Bill Watterson
3,The Harry Potter Collection,4.73,27410.0,Juvenile Fiction,http://books.google.com/books/content?id=v0z1P...,J. K. Rowling
4,Homicidal Psycho Jungle Cat,4.72,14952.0,Humor,http://books.google.com/books/content?id=-aOTQ...,Bill Watterson

In [ ]:
df_popular.shape

(50, 6)

#Feature Selection

In [ ]:
#feature selection
df = df[['title', 'authors', 'categories','description', 'average_rating','ratings_count','thumbnail']]
df.head()

,title,authors,categories,description,average_rating,ratings_count,thumbnail
0,Gilead,Marilynne Robinson,Fiction,A NOVEL THAT READERS and critics have been eag...,3.85,361.0,http://books.google.com/books/content?id=KQZCP...
1,Spider's Web,Charles Osborne;Agatha Christie,Detective and mystery stories,A new 'Christie for Christmas' -- a full-lengt...,3.83,5164.0,http://books.google.com/books/content?id=gA5GP...
2,The One Tree,Stephen R. Donaldson,American fiction,Volume Two of Stephen Donaldson's acclaimed se...,3.97,172.0,http://books.google.com/books/content?id=OmQaw...
3,Rage of angels,Sidney Sheldon,Fiction,"A memorable, mesmerizing heroine Jennifer -- b...",3.93,29532.0,http://books.google.com/books/content?id=FKo2T...
4,The Four Loves,Clive Staples Lewis,Christian life,Lewis' work on the nature of love divides love...,4.15,33684.0,http://books.google.com/books/content?id=XhQ5X...

In [ ]:
df.shape

(6810, 7)

In [ ]:
df.isnull().sum()

title               0
authors            72
categories         99
description       262
average_rating     43
ratings_count      43
thumbnail         329
dtype: int64

#data cleaning

In [ ]:
#removing null values
df = df.dropna(subset=['categories','description','thumbnail'])

In [ ]:
#filling null values
df['authors'] = df['authors'].fillna(' ')
df['average_rating'] = df['average_rating'].fillna(df['average_rating'].mean())
df['ratings_count'] = df['ratings_count'].fillna(0)

In [ ]:
df.isnull().sum()

title             0
authors           0
categories        0
description       0
average_rating    0
ratings_count     0
thumbnail         0
dtype: int64

In [ ]:
df = df.reset_index(drop=True)

In [ ]:
df.duplicated().sum()

np.int64(0)

In [ ]:
df.sample(5)

,title,authors,categories,description,average_rating,ratings_count,thumbnail
4419,Chainfire,Terry Goodkind,Fiction,Richard struggles to find his missing wife Kah...,3.96,41750.0,http://books.google.com/books/content?id=doUPJ...
4890,Practice! Practice!,Norma Goldman;Michael Rossi,Education,"Exhibiting the same clarity as Latin via Ovid,...",4.08,12.0,http://books.google.com/books/content?id=-34_q...
5662,From Nomads to Pilgrims,Diana Butler Bass;Joseph Stewart-Sicking,Religion,"In The Practicing Congregation (Alban, 2004), ...",4.00,13.0,http://books.google.com/books/content?id=e0XPP...
5708,Mother Maria Skobtsova,Mariia,Biography & Autobiography,A collection of writings that reflect the deep...,4.31,59.0,http://books.google.com/books/content?id=2vLYA...
2094,The Wolves in the Walls,Neil Gaiman,Juvenile Fiction,"Lucy hears sneaking, creeping, crumpling noise...",4.07,13382.0,http://books.google.com/books/content?id=Ksx1a...

In [ ]:
df.shape

(6304, 7)

In [ ]:
df.columns

Index(['title', 'authors', 'categories', 'description', 'average_rating',
       'ratings_count', 'thumbnail'],
      dtype='object')

In [ ]:
#creating a new column for tags
df['tags'] = df['title'] + ' ' + df['authors'] + ' ' + df['categories'] + ' ' + df['description']

In [ ]:
df.sample(5)

,title,authors,categories,description,average_rating,ratings_count,thumbnail,tags
2079,Anne Frank,Johanna Hurwitz,Juvenile Nonfiction,"From July 1942 until August 1944, a young girl...",3.99,143.0,http://books.google.com/books/content?id=3ja19...,Anne Frank Johanna Hurwitz Juvenile Nonfiction...
4161,Tinker,Wen Spencer,Fiction,"Inventor, girl genius Tinker lives in a near-f...",4.07,4362.0,http://books.google.com/books/content?id=N4gMA...,"Tinker Wen Spencer Fiction Inventor, girl geni..."
2931,Knowledge And Decisions,Thomas Sowell,Law,"With a new preface by the author, this reissue...",4.38,720.0,http://books.google.com/books/content?id=oaKSs...,Knowledge And Decisions Thomas Sowell Law With...
5996,Tramps Like Us,Yayoi Ogawa,Comics & Graphic Novels,Sumire is demoted from her job on the same day...,4.38,488.0,http://books.google.com/books/content?id=-aqNA...,Tramps Like Us Yayoi Ogawa Comics & Graphic No...
1640,Them,Jon Ronson,Political leadership,*Britain's funniest and most insightful satiri...,3.95,991.0,http://books.google.com/books/content?id=8Ea0N...,Them Jon Ronson Political leadership *Britain'...

#data preprocessing

In [ ]:
df['tags'][3]

"Rage of angels Sidney Sheldon Fiction A memorable, mesmerizing heroine Jennifer -- brilliant, beautiful, an attorney on the way up until the Mafia's schemes win her the hatred of an implacable enemy -- and a love more destructive than hate. A dangerous, dramatic world The Dark Arena of organized crime and flashbulb lit courtrooms where ambitious prosecutors begin their climb to political power."

In [ ]:
#libraries
import nltk
from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer
import re

In [ ]:
nltk.download('punkt_tab')
nltk.download('stopwords')
nltk.download('wordnet')

[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt_tab.zip.
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.
[nltk_data] Downloading package wordnet to /root/nltk_data...

True

In [ ]:
stop_words = set(stopwords.words('english'))
lemmatizer = WordNetLemmatizer()

In [ ]:
#preprocessing
def preprocess(text):

  #lowercasing
  text = text.lower()

  #remove punctuation
  text = re.sub(r'[^a-zA-Z\s]','',text)

  #tokenization
  tokens = word_tokenize(text)

  #removing stopwords
  y = []
  for i in tokens:
    if i not in stop_words:
      y.append(i)

  #lammatizing
  x = []
  for i in y:
    x.append(lemmatizer.lemmatize(i))

  return " ".join(x)

In [ ]:
df['tags'] = df['tags'].apply(preprocess)

In [ ]:
df['tags'][2]

'one tree stephen r donaldson american fiction volume two stephen donaldsons acclaimed second trilogy featuing compelling antihero thomas covenant'

In [ ]:
df.head()

,title,authors,categories,description,average_rating,ratings_count,thumbnail,tags
0,Gilead,Marilynne Robinson,Fiction,A NOVEL THAT READERS and critics have been eag...,3.85,361.0,http://books.google.com/books/content?id=KQZCP...,gilead marilynne robinson fiction novel reader...
1,Spider's Web,Charles Osborne;Agatha Christie,Detective and mystery stories,A new 'Christie for Christmas' -- a full-lengt...,3.83,5164.0,http://books.google.com/books/content?id=gA5GP...,spider web charles osborneagatha christie dete...
2,The One Tree,Stephen R. Donaldson,American fiction,Volume Two of Stephen Donaldson's acclaimed se...,3.97,172.0,http://books.google.com/books/content?id=OmQaw...,one tree stephen r donaldson american fiction ...
3,Rage of angels,Sidney Sheldon,Fiction,"A memorable, mesmerizing heroine Jennifer -- b...",3.93,29532.0,http://books.google.com/books/content?id=FKo2T...,rage angel sidney sheldon fiction memorable me...
4,The Four Loves,Clive Staples Lewis,Christian life,Lewis' work on the nature of love divides love...,4.15,33684.0,http://books.google.com/books/content?id=XhQ5X...,four love clive staple lewis christian life le...

In [ ]:
#extracting indices with index
indices = pd.Series(df.index,index=df['title'])
indices.head()

title
Gilead            0
Spider's Web      1
The One Tree      2
Rage of angels    3
The Four Loves    4
dtype: int64

In [ ]:
indices.shape

(6304,)

#vectorization

In [ ]:
#tfidf
from sklearn.feature_extraction.text import TfidfVectorizer
tfidf = TfidfVectorizer(max_features=10000,ngram_range=(1,2))

In [ ]:
tfidf_matrix = tfidf.fit_transform(df['tags'])

In [ ]:
tfidf_matrix

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 230098 stored elements and shape (6304, 10000)>

In [ ]:
tfidf_matrix.toarray()

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [ ]:
df.shape

(6304, 8)

#Recommendation using cosine similarity

In [ ]:
from sklearn.metrics.pairwise import cosine_similarity

In [ ]:
#recomendation function
def recommend(title,n=10):
  if title not in indices:
    return ['Book not found']

  idx = indices[title]
  sim_score = cosine_similarity(tfidf_matrix[idx], tfidf_matrix).flatten()
  similar_idx = sim_score.argsort()[::-1][1:n+1]
  return df.iloc[similar_idx]

In [ ]:
recommend("Spider's Web")

,title,authors,categories,description,average_rating,ratings_count,thumbnail,tags
1542,Black Coffee,Agatha Christie,Fiction,Master sleuth Hercule Poirot and Captain Hasti...,3.48,9592.0,http://books.google.com/books/content?id=-VhVp...,black coffee agatha christie fiction master sl...
53,The Hollow,Agatha Christie,Detective and mystery stories,Lucy Angkatell Invited Hercule Poirot To Lunch...,3.79,13022.0,http://books.google.com/books/content?id=-f1h4...,hollow agatha christie detective mystery story...
16,Witness for the Prosecution & Selected Plays,Agatha Christie,English drama,Newly-Jacketed Edition Designed To Celebrate T...,4.05,3908.0,http://books.google.com/books/content?id=_9u7A...,witness prosecution selected play agatha chris...
6,An Autobiography,Agatha Christie,"Authors, English",Donation.,4.27,3975.0,http://books.google.com/books/content?id=c49GQ...,autobiography agatha christie author english d...
71,The Listerdale Mystery,Agatha Christie,Detective and mystery stories,"A selection of mysteries, some light-hearted, ...",3.55,178.0,http://books.google.com/books/content?id=J1tLG...,listerdale mystery agatha christie detective m...
2365,Hercule Poirot's Casebook,Agatha Christie,Detective and mystery stories,"Here, for the first time in one volume, is the...",4.30,1852.0,http://books.google.com/books/content?id=okVDk...,hercule poirots casebook agatha christie detec...
46,The Big Four,Agatha Christie,Detective and mystery stories,A ruthless international cartel seeks world do...,3.59,22155.0,http://books.google.com/books/content?id=wcOQU...,big four agatha christie detective mystery sto...
49,A Murder is Announced,Agatha Christie,"Detective and mystery stories, English",The villagers of Chipping Cleghorn are amazed ...,3.98,680.0,http://books.google.com/books/content?id=QEEvz...,murder announced agatha christie detective mys...
5756,The Body in the Library,Agatha Christie,Fiction,Miss Marple investigates the death of a stylis...,3.85,43669.0,http://books.google.com/books/content?id=hcgee...,body library agatha christie fiction miss marp...
2397,The Regatta Mystery and Other Stories,Agatha Christie,Fiction,Nine tales of mystery and murder are marked by...,3.95,5701.0,http://books.google.com/books/content?id=36hHP...,regatta mystery story agatha christie fiction ...

#saving model

In [ ]:
import pickle

pickle.dump(tfidf_matrix,open('tfidf_matrix.pkl','wb')) #tfidf matrix

pickle.dump(indices,open('indices.pkl','wb')) #indices

df.to_pickle('df.pkl') #books

pickle.dump(tfidf,open('tfidf.pkl','wb')) #tfidf

pickle.dump(df_popular,open('df_popular.pkl','wb')) #top 50